name: Terraform CI/CD

on:
  workflow_dispatch:  # Для ручного запуска
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  terraform-checks:
    name: "Terraform Checks (${{ matrix.path }})"
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path: [clickhouse, postgres, redis]
    steps:
      - uses: actions/checkout@v4
