name: Terraform CI/CD

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  terraform-checks:
    name: "Terraform Checks"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Debug
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "This job should never be skipped!"
