name: Terraform CI/CD

on:
  workflow_dispatch:  # Ручной запуск
  push:
    branches: [master]  # Триггер на push в master
  pull_request:
    branches: [master]  # Триггер на PR в master

jobs:
  terraform-plan:
    name: "Terraform Checks (${{ matrix.path }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path: [clickhouse, postgres, redis]  # Матрица конфигураций
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Terraform Format
        run: terraform -chdir=${{ matrix.path }} fmt -check -recursive
        
      - name: Terraform Init
        run: terraform -chdir=${{ matrix.path }} init -input=false
      
      - name: Terraform Validate
        run: terraform -chdir=${{ matrix.path }} validate -no-color
      
      - name: Terraform Plan
        run: terraform -chdir=${{ matrix.path }} plan -out=tfplan -input=false

  terraform-apply:
    name: "Apply (${{ matrix.path }})"
    needs: terraform-plan
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    environment:
      name: production
    strategy:
      matrix:
        path: [clickhouse, postgres, redis]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2
        
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
          
      - name: Terraform Init
        run: terraform -chdir=${{ matrix.path }} init
        
      - name: Terraform Apply
        run: terraform -chdir=${{ matrix.path }} apply -auto-approve
        
      - name: Verify container
        run: |
          sleep 30
          docker ps -a
          docker inspect ${{ matrix.path }}
          
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install requests psycopg2-binary clickhouse-driver redis
          pip show requests psycopg2-binary clickhouse-driver redis
            
      - name: Load data
        run: |
          source venv/bin/activate
          python scripts/load_data.py
