name: Terraform CI/CD

on:
  workflow_dispatch:  # Для ручного запуска
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  terraform-checks:
    name: "Terraform Checks (${{ matrix.path }})"
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path: [clickhouse, postgres, redis]
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.4.0
      
      - name: Terraform Format
        run: terraform -chdir=${{ matrix.path }} fmt -check
      
      - name: Terraform Init
        run: terraform -chdir=${{ matrix.path }} init -input=false
      
      - name: Terraform Validate
        run: terraform -chdir=${{ matrix.path }} validate -no-color
      
      - name: Terraform Plan
        run: terraform -chdir=${{ matrix.path }} plan -out=tfplan -input=false
