name: Terraform CI/CD

on:
  workflow_dispatch:  # Для ручного запуска
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  terraform-checks:
    name: "Terraform Checks (${{ matrix.path }})"
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path: [clickhouse, postgres, redis]
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.4.0
      
      - name: Terraform Format
        run: terraform -chdir=${{ matrix.path }} fmt -check
      
      - name: Terraform Init
        run: terraform -chdir=${{ matrix.path }} init -input=false
      
      - name: Terraform Validate
        run: terraform -chdir=${{ matrix.path }} validate -no-color
      
      - name: Terraform Plan
        run: terraform -chdir=${{ matrix.path }} plan -out=tfplan -input=false

  terraform-apply:
    name: "Terraform Apply (${{ matrix.path }})"
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: terraform-checks
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix:
        path: [clickhouse, postgres, redis]
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.4.0
      
      - name: Terraform Apply
        run: terraform -chdir=${{ matrix.path }} apply -auto-approve -input=false

  load-data:
    name: "Load Test Data"
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: terraform-apply
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests psycopg2-binary clickhouse-driver redis
      
      - name: Load data
        run: python scripts/load_data.py
